# Generated by Django 3.2.7 on 2021-09-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1023)),
                ('rate', models.PositiveSmallIntegerField(default=0)),
                ('number_of_rates', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
    ]
